put http://localhost:3000/user/466a22ad-82e6-4479-91a1-74d38382c144 HTTP/1.1
content-type: application/json

{
    "name":"Martin",
    "email":"guerovera37@gmail.com",
    "password":"superpassword"
}

###

delete http://localhost:3000/user/35927ea0-fc52-4b6e-bd58-9149b89267b6 HTTP/1.1